name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    uses: AimenFH/WebEngineering_BaseTemplate/.github/workflows/common-steps.yml@main

  build-and-deploy-steps:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist